### PR TITLE
Week 1 Problems pull request

### PR DESCRIPTION
**Pull request by beyucel**
## Description
Answers for the Week 1 Problem set

## Weekly Journal
Prof. Chow's  Slides and his explanations for Python basics were really helpful. However, he couldn't cover his final slides due to time restriction. The topics on his final slides were the topics that are really important for me (Classes, objects,__init__ etc). I hope we can get some information about object-oriented programming for the remaining part of the workshop. Git-GitHub introduction was really helpful. I hope there will be advanced git-GitHub tasks for the upcoming weeks so that I can get better at git and GitHub

## Questions
- [ 1] I was mostly using Matlab for my research and I am trying to switch to Python. In Matlab, It was really easy to check variables and I could easily use the command window to do simple calculations without running the whole code. Can I do similar operations on Python? Also is it possible to run some section of the code(like highlighting it and selecting run highlighted section)? or do I need to use the debugger for that task?

Thanks,

### CODE REVIEW

**Comment by dsirianni** [comment]
To answer your question regarding the Matlab-like capabilities of Python programming: kinda yes, kinda no.  

The reason is because you're conflating Matlab and Python in two different contexts here: Matlab the **IDE** (**I**nteractive **D**evelopment **E**nvironment), which is a program within which to write, view, and run/debug code, and Matlab/Python the **language**.  Even though Python is just a language, there are, a plethora of IDEs for Python out there.  

Likely the closest IDE to Matlab (the program) is [Spyder](https://pythonhosted.org/spyder/), but my personal Python IDE of choice are [Jupyter Notebooks](http://jupyter.org/), which look more like Mathematica notebooks and can combine figures, text, LaTeX-rendered mathematics, and executable code.  You can check out [this interactive tutorial](https://github.com/psi4/psi4numpy/blob/master/Tutorials/03_Hartree-Fock/3c_unrestricted-hartree-fock.ipynb), part of the [Psi4NumPy project](https://github.com/psi4/psi4numpy), to see how these notebooks can be really powerful tools to make Python workflows really slick.  We'll actually be using them later in the workshop, too.

**Comment by beyucel** [comment]
Thank you for your quick and helpful response, Dominic.

**Comment by beyucel** [comment]
I added the second assignment (actually, once I commit my changes to my fork repo, it automatically submitted the new assignment as an addition to previous pull request), but I could not send a separate pull request. Is it what it should be? or am I making a mistake?

**Comment by dsirianni** [comment]
@beyucel you aren't making a mistake, just doing what you knew how to do.  For now, I'm assigning @bencomer to take a look at your Week 02 submission, and he can merge your PR as soon as he's approved that assignment.  

I would advocate that you check out my announcements on [keeping your fork up-to-date](https://github.com/GT-IDEaS/SkillsWorkshop2018/blob/master/Announcements/01_Updating-your-fork.md) and [branching & the GitHub flow](https://github.com/GT-IDEaS/SkillsWorkshop2018/blob/master/Announcements/02_Branching-and-the-GH-flow.md), the combination of which allow you to make separate PRs for each assignment.

**Comment by beyucel** [comment]
Thanks, Dominic!

**Comment by beyucel** [comment]
Hey Ben, I fixed the problem with the BIC calculation. BIC results are really close  like : 
BIC for linear curve is : 29.97949134672216 
BIC for Cubic curve is : 30.360576141400536
So I know that increasing the degree will always increase the possibility of the overfitting. How would you decide between cubic and linear in this circumstances(close BIC result)? Because I would not be very sure, I guess I would do cross-validation to check if I am overfitting or not.

**Comment by bencomer** [comment]
Thanks! 

I would say that if the BIC is close then it's a judgement call on which one is better. BIC is not really a hard way to say "pick this one" but it is a good guide. I actually made the data using a cubic function and adding noise, so the "true" model is cubic. But, a linear model approximates it very well over this range, so linear might be the better choice. 

Cross validation is another legitimate strategy for deciding what model to choose, and is probably superior to BIC. I was going to go over it but realized I wouldn't have time.

**Pull request merged**
